//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::ads::Entity as Ads;
pub use super::auth::Entity as Auth;
pub use super::categories::Entity as Categories;
pub use super::players_graph::Entity as PlayersGraph;
pub use super::reviews::Entity as Reviews;
pub use super::server_categories::Entity as ServerCategories;
pub use super::servers::Entity as Servers;
pub use super::servers_info::Entity as ServersInfo;
pub use super::users::Entity as Users;
pub use super::versions::Entity as Versions;
